#!/bin/bash

headerflag=1

echo "" > season_stats.csv
for ((year=2014;i<2014;i+=1))
do 
	for ((month=11;month<=11;month+=1))
	do
		for ((day=22;day<=22;day+=1))
		do
			./scrape_day $headerflag $year $month $day
			headerflag=0
		done
	done
done
